package com.example.cardmaximizer.model;

public enum Category {
    GAS_COSTCO, GAS_ESSO, DINING, GROCERY_LOBLAWS,
    GROCERY_EMPIRE, COSTCO_WAREHOUSE, TRAVEL_EXPEDIA,
    GAMING_DIGITAL, RECURRING_BILL, OTHER,PUBLIC_TRANSIT,
    GROCERY,ENTERTAINMENT,SHOPPERS_DRUG_MART,GAS,ONLINE_COSTCO
}